# Generated by Django 3.0.5 on 2020-04-30 10:25

from django.db import migrations


def add_status(apps, schema_editor):
    status = apps.get_model('events', 'Status')
    status.objects.create(status=0)
    status.objects.create(status=1)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_status),
    ]
