# Generated by Django 3.0.5 on 2020-04-22 12:57

from django.db import migrations


def add_status(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Status = apps.get_model('events', 'Status')
    Status.objects.create(status=0)
    Status.objects.create(status=1)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_status),
    ]
